"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Check, ChevronLeft, ChevronRight, RotateCcw, Save } from "lucide-react";
import { useWorkspace } from "@/features/workspace/workspace-store";
import { Button, PageHeading } from "@/components/ui/primitives";

export function SuitConfigurator() {
  const params = useSearchParams(); const groups = useWorkspace((s) => s.groups); const initialSettings = useMemo(() => Object.fromEntries(groups.map((group) => [group.key, group.options[0]?.key || ""])), [groups]); const allFabrics = useWorkspace((s) => s.fabrics); const fabrics = useMemo(() => allFabrics.filter((fabric) => fabric.isActive), [allFabrics]); const configurations = useWorkspace((s) => s.configurations); const saveConfiguration = useWorkspace((s) => s.saveConfiguration); const source = configurations.find((c) => c.id === params.get("id"));
  const [fabricId, setFabricId] = useState(params.get("fabric") || source?.fabricId || fabrics[0]?.id || ""); const [settings, setSettings] = useState<Record<string,string>>(source?.settings || initialSettings); const [step, setStep] = useState(0); const [name, setName] = useState(source?.name || "Новая конфигурация"); const [saved, setSaved] = useState(false); const selectedFabric = fabrics.find((f) => f.id === fabricId); const group = step === 0 ? undefined : groups[step - 1];
  const progress = Math.round(((step + 1) / (groups.length + 1)) * 100); const summary = useMemo(() => groups.map((g) => ({ group: g.name, option: g.options.find((o) => o.key === settings[g.key])?.name || "—" })), [settings, groups]);
  useEffect(() => { const before = (event: BeforeUnloadEvent) => { if (!saved) event.preventDefault(); }; window.addEventListener("beforeunload", before); return () => window.removeEventListener("beforeunload", before); }, [saved]);
  async function save() { const now = new Date().toISOString(); await saveConfiguration({ id: source?.id || crypto.randomUUID(), name: name.trim() || "Без названия", fabricId, settings, createdAt: source?.createdAt || now, updatedAt: now }); setSaved(true); }
  return <div className="space-y-7"><PageHeading eyebrow="Сборка костюма" title="Конфигуратор" description="Параметры загружаются из групп и опций. 3D-просмотр исключён из этой версии по вашему указанию." />
    <div className="h-1 bg-[#ddd5ca]" aria-label={`Прогресс ${progress}%`} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><div className="h-full bg-[#7a2635] transition-[width]" style={{ width: `${progress}%` }} /></div>
    <div className="grid gap-7 xl:grid-cols-[minmax(0,.9fr)_minmax(360px,1.1fr)]">
      <section className="surface overflow-hidden"><div className={`fabric-swatch ${selectedFabric?.swatch || "charcoal"} relative min-h-[430px] sm:min-h-[560px]`}>
        <div className="absolute inset-0 z-10 flex items-center justify-center"><div className="relative h-[72%] w-[54%] max-w-[330px] min-w-[240px]" aria-label="Плоский эскиз костюма"><div className="absolute left-[9%] top-0 h-[70%] w-[82%] bg-[#e9e3d8] shadow-2xl [clip-path:polygon(22%_0,43%_8%,50%_32%,57%_8%,78%_0,100%_16%,84%_38%,81%_100%,19%_100%,16%_38%,0_16%)]" /><div className="absolute left-[30%] top-[11%] h-[41%] w-[40%] border-x-[24px] border-transparent border-t-[92px] border-t-[#cfc6b7]" /><div className="absolute bottom-0 left-[22%] h-[39%] w-[25%] bg-[#ddd6ca] [clip-path:polygon(0_0,100%_0,82%_100%,0_100%)]" /><div className="absolute bottom-0 right-[22%] h-[39%] w-[25%] bg-[#ddd6ca] [clip-path:polygon(0_0,100%_0,100%_100%,18%_100%)]" /></div></div>
        <div className="absolute bottom-4 left-4 right-4 z-10 bg-[#f8f5ef]/95 p-4"><p className="eyebrow">Материал</p><b className="mt-1 block text-sm">{selectedFabric?.name}</b><span className="muted text-xs">{selectedFabric?.article} · {selectedFabric?.composition}</span></div>
      </div></section>
      <section className="surface flex min-h-[560px] flex-col p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">Шаг {step + 1} из {groups.length + 1}</p><h2 className="font-display mt-2 text-3xl font-normal">{step === 0 ? "Ткань" : group?.name}</h2></div><Button variant="quiet" onClick={() => { setSettings(initialSettings); setSaved(false); }}><RotateCcw size={16} /> Сбросить</Button></div>
        <div className="mt-7 flex-1">{step === 0 ? <div className="grid gap-3 sm:grid-cols-2">{fabrics.map((fabric) => <button key={fabric.id} type="button" className={`grid grid-cols-[68px_1fr_auto] items-center gap-3 border p-2 text-left ${fabric.id === fabricId ? "border-[#7a2635] bg-[#f7efee]" : "border-[#d3ccc0]"}`} onClick={() => { setFabricId(fabric.id); setSaved(false); }}><span className={`fabric-swatch ${fabric.swatch} size-[68px]`} /><span><b className="block text-xs">{fabric.name}</b><small className="muted">{fabric.article}</small></span>{fabric.id === fabricId && <Check size={17} className="text-[#7a2635]" />}</button>)}</div> : <div className="space-y-3">{group?.options.map((option) => <button key={option.id} type="button" className={`flex min-h-[68px] w-full items-center justify-between gap-4 border p-4 text-left ${settings[group.key] === option.key ? "border-[#7a2635] bg-[#f7efee]" : "border-[#d3ccc0]"}`} onClick={() => { setSettings((current) => ({ ...current, [group.key]: option.key })); setSaved(false); }}><span><b className="block text-sm">{option.name}</b>{option.description && <small className="muted mt-1 block">{option.description}</small>}</span>{settings[group.key] === option.key && <Check size={18} className="text-[#7a2635]" />}</button>)}</div>}</div>
        <div className="mt-7 flex items-center justify-between border-t border-[#d3ccc0] pt-5"><Button variant="secondary" onClick={() => setStep((s) => Math.max(0, s - 1))} disabled={step === 0}><ChevronLeft size={17} /> Назад</Button>{step < groups.length ? <Button onClick={() => setStep((s) => Math.min(groups.length, s + 1))}>Далее <ChevronRight size={17} /></Button> : <span />}</div>
      </section>
    </div>
    {step === groups.length && <section className="surface p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><label className="label" htmlFor="configuration-name">Название конфигурации</label><input id="configuration-name" className="input max-w-xl" value={name} onChange={(e) => { setName(e.target.value); setSaved(false); }} /></div><Button onClick={save}><Save size={17} />{saved ? "Сохранено" : "Сохранить конфигурацию"}</Button></div><dl className="mt-7 grid gap-px border border-[#d3ccc0] bg-[#d3ccc0] sm:grid-cols-2 lg:grid-cols-3">{summary.map((item) => <div key={item.group} className="bg-[#f8f5ef] p-4"><dt className="muted text-xs">{item.group}</dt><dd className="mt-1 text-sm font-bold">{item.option}</dd></div>)}</dl></section>}
  </div>;
}
