"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, FileSpreadsheet, UploadCloud, XCircle } from "lucide-react";
import * as XLSX from "xlsx";
import { validateImportRows } from "@/lib/import";
import { useWorkspace } from "@/features/workspace/workspace-store";
import { Button, ButtonLink, PageHeading } from "@/components/ui/primitives";

const aliases: Record<string,string> = { артикул: "article", article: "article", название: "name", name: "name", производитель: "manufacturer", manufacturer: "manufacturer", цвет: "mainColor", pattern: "pattern", рисунок: "pattern", состав: "composition", цена: "pricePerMeter" };

export function ImportWorkspace() {
  const inputRef = useRef<HTMLInputElement>(null); const addFabric = useWorkspace((state) => state.addFabric); const [filename, setFilename] = useState(""); const [rows, setRows] = useState<Record<string,unknown>[]>([]); const [done, setDone] = useState(false); const result = validateImportRows(rows);
  async function readFile(file?: File) { if (!file) return; setDone(false); setFilename(file.name); const workbook = XLSX.read(await file.arrayBuffer(), { type: "array" }); const raw = XLSX.utils.sheet_to_json<Record<string,unknown>>(workbook.Sheets[workbook.SheetNames[0]!]!, { defval: "" }); setRows(raw.map((row) => Object.fromEntries(Object.entries(row).map(([key,value]) => [aliases[key.trim().toLocaleLowerCase("ru")] || key, value])))); }
  function importRows() { const now = new Date().toISOString(); result.valid.forEach((raw) => addFabric({ id: crypto.randomUUID(), article: String(raw.article), name: String(raw.name), manufacturer: String(raw.manufacturer || "Не указана"), collection: String(raw.collection || ""), composition: String(raw.composition || "Не указано"), mainColor: String(raw.mainColor || "Не указан"), pattern: String(raw.pattern || "Не указан"), weightGsm: Number(raw.weightGsm || 0), widthCm: Number(raw.widthCm || 0), pricePerMeter: Number(raw.pricePerMeter || 0), currency: "RUB", description: String(raw.description || ""), isActive: true, swatch: "charcoal", createdAt: now, updatedAt: now })); setDone(true); }
  return <div className="space-y-8"><PageHeading eyebrow="Массовое добавление" title="Импорт тканей" description="Загрузите XLSX, XLS или CSV. Заголовки на русском и английском распознаются автоматически." actions={<ButtonLink href="/fabrics" variant="secondary"><ArrowLeft size={17} /> Каталог</ButtonLink>} />
    {!rows.length ? <section className="surface grid min-h-[360px] place-items-center p-8 text-center"><div><FileSpreadsheet className="mx-auto mb-5 text-[#7a2635]" size={42} /><h2 className="font-display text-3xl font-normal">Выберите таблицу</h2><p className="muted mx-auto mt-3 max-w-md text-sm leading-6">Обязательные столбцы: «Артикул» и «Название». Перед импортом вы увидите проверку каждой строки.</p><Button className="mt-6" onClick={() => inputRef.current?.click()}><UploadCloud size={18} /> Выбрать файл</Button><input ref={inputRef} className="sr-only" type="file" accept=".xlsx,.xls,.csv" onChange={(e) => readFile(e.target.files?.[0])} /></div></section> : <>
      <section className="grid gap-px border border-[#d3ccc0] bg-[#d3ccc0] sm:grid-cols-3"><div className="bg-[#f8f5ef] p-5"><p className="muted text-xs">Файл</p><b className="mt-2 block truncate text-sm">{filename}</b></div><div className="bg-[#f8f5ef] p-5"><p className="muted text-xs">Готовы к импорту</p><b className="mt-2 flex items-center gap-2 text-sm text-[#34523e]"><CheckCircle2 size={17} /> {result.valid.length} строк</b></div><div className="bg-[#f8f5ef] p-5"><p className="muted text-xs">Требуют исправления</p><b className="mt-2 flex items-center gap-2 text-sm text-[#8b2435]"><XCircle size={17} /> {result.invalid.length} строк</b></div></section>
      <section><div className="rule-title"><h2>Предпросмотр</h2><span className="muted text-xs">Первые 50 строк</span></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-left text-sm"><thead><tr className="border-b border-[#d3ccc0] text-xs uppercase tracking-[.08em] text-[#6d6a63]"><th className="p-3">Строка</th><th className="p-3">Артикул</th><th className="p-3">Название</th><th className="p-3">Производитель</th><th className="p-3">Результат</th></tr></thead><tbody>{rows.slice(0,50).map((row,index) => { const issue = result.invalid.find((item) => item.row === index + 2); return <tr key={index} className="border-b border-[#ded8ce]"><td className="p-3">{index + 2}</td><td className="p-3 font-bold">{String(row.article || "—")}</td><td className="p-3">{String(row.name || "—")}</td><td className="p-3">{String(row.manufacturer || "—")}</td><td className="p-3">{issue ? <span className="text-[#8b2435]">{issue.issues.join(", ")}</span> : <span className="text-[#34523e]">Готово</span>}</td></tr>; })}</tbody></table></div></section>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#d3ccc0] pt-5"><Button variant="secondary" onClick={() => { setRows([]); setDone(false); }}>Выбрать другой файл</Button>{done ? <p role="status" className="flex items-center gap-2 font-bold text-[#34523e]"><CheckCircle2 size={18} /> Импортировано: {result.valid.length}. <Link href="/fabrics" className="underline">Открыть каталог</Link></p> : <Button onClick={importRows} disabled={!result.valid.length}>Импортировать {result.valid.length} строк</Button>}</div>
    </>}
  </div>;
}
