"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Copy, Plus, Scale, Trash2 } from "lucide-react";
import { formatDate } from "@/lib/utils";
import { useWorkspace } from "@/features/workspace/workspace-store";
import { Button, ButtonLink, PageHeading } from "@/components/ui/primitives";

export function ConfigurationsList() {
  const configurations = useWorkspace((s) => s.configurations); const groups = useWorkspace((s) => s.groups); const fabrics = useWorkspace((s) => s.fabrics); const save = useWorkspace((s) => s.saveConfiguration); const remove = useWorkspace((s) => s.deleteConfiguration); const [selected, setSelected] = useState<string[]>([]);
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((x) => x !== id) : current.length < 2 ? [...current, id] : [current[1]!, id]); }
  return <div className="space-y-8"><PageHeading eyebrow="Сохранённые варианты" title="Конфигурации" description="Выберите два варианта, чтобы увидеть различия по каждому параметру." actions={<><ButtonLink href={`/configurations/compare?left=${selected[0] || ""}&right=${selected[1] || ""}`} variant="secondary" aria-disabled={selected.length !== 2}><Scale size={17} /> Сравнить {selected.length}/2</ButtonLink><ButtonLink href="/configurator"><Plus size={17} /> Новая</ButtonLink></>} />
    {!configurations.length ? <div className="empty-state"><h2 className="font-display text-3xl">Конфигураций пока нет</h2><ButtonLink href="/configurator" className="mt-5">Собрать первую</ButtonLink></div> : <div className="divide-y divide-[#d3ccc0] border-y border-[#d3ccc0]">{configurations.map((item) => { const fabric = fabrics.find((f) => f.id === item.fabricId); return <article key={item.id} className="grid gap-4 py-5 sm:grid-cols-[auto_78px_1fr_auto] sm:items-center"><label className="grid size-11 cursor-pointer place-items-center border border-[#c3bbae]"><span className="sr-only">Выбрать {item.name} для сравнения</span><input type="checkbox" className="size-4 accent-[#7a2635]" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} /></label><div className={`fabric-swatch ${fabric?.swatch || "charcoal"} size-[78px]`} /><div><Link href={`/configurator?id=${item.id}`} className="font-display text-xl text-inherit no-underline">{item.name}</Link><p className="muted mt-1 text-xs">{fabric?.name || "Ткань не выбрана"} · обновлено {formatDate(item.updatedAt)}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1">{groups.slice(0,3).map((g) => <span key={g.key} className="text-[11px]"><span className="muted">{g.name}:</span> {g.options.find((o) => o.key === item.settings[g.key])?.name}</span>)}</div></div><div className="flex items-center gap-1"><Button variant="quiet" aria-label={`Дублировать ${item.name}`} onClick={() => { const now = new Date().toISOString(); save({ ...item, id: crypto.randomUUID(), name: `${item.name} — копия`, createdAt: now, updatedAt: now }); }}><Copy size={17} /></Button><Button variant="quiet" aria-label={`Удалить ${item.name}`} onClick={() => { if (window.confirm(`Удалить конфигурацию «${item.name}»?`)) remove(item.id); }}><Trash2 size={17} /></Button><Link href={`/configurator?id=${item.id}`} className="icon-button" aria-label={`Открыть ${item.name}`}><ArrowRight size={17} /></Link></div></article>; })}</div>}
  </div>;
}
